### ISSUE TITLE
lack values at "剩余日"

### ISSUE THREAD

**Issue by Succee** [yulu0131/optshare#1]
When using get_commodity_option to obtain commodity option basic info，there are NaNs. I know no values at the response，but how to fix it?

**Comment by yulu0131** [comment]
I don't think I have included an API interface called 'get_commodity_option' to obtain commodity option info, you can use ‘get_commodity_option_quotes()’ instead to fetch commodity option T quotes data given by the exchange name.
Please read the online documentation "https://optshare.readthedocs.io/en/latest/index.html" for more information.

**Comment by Succee** [comment]
I just think this item belongs to basic info , not belongs to quotes.  So Thank you for your answer!
